name: bloc_rx
description: A simlpe implementation of BLoC with rxdart!
version: 1.0.0
homepage: https://twitter.com/tihrasguinho

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
